version: '3'
services:
  postgres:
    image: postgres:15-alpine
    ports:
      - '5432:5432'
    volumes:
      - ./docker/init-postgres.sql:/docker-entrypoint-initdb.d/init-postgres.sql
    environment:
      POSTGRES_DB: wallet
      POSTGRES_USER: wallet_app
      POSTGRES_PASSWORD: secret

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - '2182:2181'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      KAFKA_HEAP_OPTS: -Xmx64m

  kafka:
    image: wurstmeister/kafka:2.13-2.8.1
    ports:
      - '9092:9092'
    depends_on:
      - zookeeper
    environment:
      KAFKA_LISTENERS: 'INTERNAL://kafka:9090,EXTERNAL://:9092'
      KAFKA_ADVERTISED_LISTENERS: 'INTERNAL://kafka:9090,EXTERNAL://kafka:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: 'transaction.request.v1:3:1,transaction.response.v1:3:1,player.event.v1:1:1'

  server:
    build:
      dockerfile: server/Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - postgres
      - kafka

  client:
    build:
      dockerfile: client/Dockerfile
    depends_on:
      - server
