walletServerUrl: http://server:8080

kafka:
  bootstrapServers: kafka:9092
  transactionRequestTopic: transaction.request.v1
  transactionResponseTopic: transaction.response.v1
  playerEventTopic: player.event.v1
  groupId: wallet-client

transaction:
  responseConsumerCount: 3
  generatedAmountMaximum: 1200.0
  delayBetweenRequestsMillis: 100
